# Node.js with webpack
# Build a Node.js project using the webpack CLI.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
name: 0.1.$(Rev:.r)

resources:
  pipelines: 
  - pipeline: BuildPipeline
    source: Maetis.ado-git-repositories-overview

stages:
  - stage: PublishDev
    jobs:
      - job: PublishDev
        pool: 
          vmImage: 'ubuntu-latest'
        steps:
          - task: TfxInstaller@3
            inputs:
              version: 'v0.8.x'
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'specific'
              project: '108190d0-bc81-465e-be7e-0a32f0bccf98'
              pipeline: '22'
              specificBuildWithTriggering: true
              buildVersionToDownload: 'latest'
              downloadType: 'specific'
              downloadPath: '$(System.ArtifactsDirectory)'
          - task: PublishAzureDevOpsExtension@3
            inputs:
              connectTo: 'VsTeam'
              connectedServiceName: 'MarketPlace'
              fileType: 'vsix'
              vsixFile: '$(System.ArtifactsDirectory)/*-dev.vsix'
