# Node.js with webpack
# Build a Node.js project using the webpack CLI.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
name: 0.1.$(Rev:.r)

resources:
  pipelines: 
  - pipeline: BuildPipeline
    source: Maetis.ado-git-repositories-overview

stages:
  - stage: PublishDev
    jobs:
      - job: PublishDev
        pool: 
          vmImage: 'ubuntu-latest'
        steps:
          - task: PublishAzureDevOpsExtension@3
            inputs:
              connectTo: 'VsTeam'
              connectedServiceName: 'MarketPlace'
              fileType: 'vsix'
              vsixFile: '*-dev.vsix'
